name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterhub=4.1.4
  - pyenv
  - pip

# Pip packages
  - pip:
    - jupyterhub-nativeauthenticator
    - jupyterhub-ldapauthenticator
    - dockerspawner
    - wrapspawner
    - batchspawner
    - jupyterhub-idle-culler
