name: base
channels:
  - conda-forge
dependencies:
  - python=3.11
  - jupyterhub=4.1.5
  - pip

# Pip packages
  - pip:
    - jupyterhub-nativeauthenticator
    - dockerspawner
    - wrapspawner
    - batchspawner
    - jupyterhub-idle-culler
    - pyenv
