name: base
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyterhub=4.0.2 
  - dockerspawner
  - jupyterhub-idle-culler
  - pip

# Pip packages
  - pip:
      - jupyterhub-nativeauthenticator
